spring:
  application:
    name: user-service
  config:
    import:
#      - 'optional:file:.env' 이것 대신 Intellij의 Edit Configuration에서 환경 변수 선택
      - "optional:configserver:${CONFIG_SERVER_URL}"
  cloud:
    config:
      enabled: true
      name: user-service
  profiles:
    active: docker
server:
  port: ${SERVER_PORT:8080}
